import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import axios from './axiosConfig';

function Buy() {
  const [properties, setProperties] = useState([]);
  const [loading, setLoading] = useState(true);
  const [bedrooms, setBedrooms] = useState('');
  const [bathrooms, setBathrooms] = useState('');
  const [priceRange, setPriceRange] = useState('');


  useEffect(() => {
    const fetchProperties = async () => {
      try {
        setLoading(true);
        const response = await axios.get('/property');
        console.log('Properties response:', response.data);
        if (response.data.success && Array.isArray(response.data.data)) {
          setProperties(response.data.data);
        } else {
          console.error('Unexpected response format:', response.data);
          setProperties([]);
        }
      } catch (error) {
        console.error('Error fetching properties:', error);
        setProperties([]);
      } finally {
        setLoading(false);
      }
    };

    fetchProperties();
  }, []);

  const handleBuyProperty = async (property) => {
    // Check if user is logged in
    const token = localStorage.getItem('token');
    const userId = localStorage.getItem('userId'); // Get actual user ID

    if (!token || !userId) {
      alert('Please login to purchase a property');
      return;
    }

    // Check if property is already sold
    if (property.isSold) {
      alert('This property is already sold');
      return;
    }

    // Confirm purchase
    const confirmPurchase = window.confirm(
      `Are you sure you want to purchase this property?\n\n` +
      `Address: ${property.address}\n` +
      `Price: $${property.price.toLocaleString()}\n` +
      `Beds: ${property.beds} | Baths: ${property.baths}`
    );

    if (!confirmPurchase) {
      return;
    }

    try {
      // Create transaction
      const transactionData = {
        propertyId: property._id,
        buyerId: userId, // Use actual user ID from localStorage
        sellerId: property.sellerId,
        // timestamp is auto-generated by server
      };

      console.log('Transaction data:', transactionData); // Debug log

      const response = await axios.post('/transaction', transactionData);

      if (response.data.success) {
        alert('🎉 Congratulations! Property purchased successfully!');

        // Refresh properties to show updated status
        const updatedResponse = await axios.get('/property');
        if (updatedResponse.data.success && Array.isArray(updatedResponse.data.data)) {
          setProperties(updatedResponse.data.data);
        }
      } else {
        alert('Failed to complete purchase. Please try again.');
      }
    } catch (error) {
      console.error('Error purchasing property:', error);
      console.error('Error response:', error.response?.data); // Debug log

      if (error.response?.status === 401) {
        alert('Session expired. Please login again.');
        localStorage.removeItem('token');
        localStorage.removeItem('userId');
        window.location.href = '/';
      } else {
        const errorMessage = error.response?.data?.message || 'Failed to purchase property. Please try again.';
        alert(errorMessage);
      }
    }
  };

  const filterProperties = () => {
    return properties.filter(property => {
      // Filter by bedrooms
      if (bedrooms && property.beds !== parseInt(bedrooms)) {
        return false;
      }
      // Filter by bathrooms
      if (bathrooms && property.baths !== parseInt(bathrooms)) {
        return false;
      }
      // Filter by price range
      if (priceRange) {
        const [minPrice, maxPrice] = priceRange.split('-').map(Number);
        if (property.price < minPrice || (maxPrice && property.price > maxPrice)) {
          return false;
        }
      }
      return true;
    });
  };
  const filteredProperties = filterProperties();

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-100 p-4 flex items-center justify-center">
        <div className="text-xl">Loading properties...</div>
      </div>
    );
  }

  if (properties.length === 0) {
    return (
      <div className="min-h-screen bg-gray-100 p-4">
        <div className="flex items-center justify-between mb-4">
          <h1 className="text-2xl font-bold">RealEstate</h1>
          <Link to="/">
            <button className="bg-blue-500 text-white px-2 py-1 rounded">Back to Home</button>
          </Link>
        </div>
        <div className="text-center mt-10 text-xl text-gray-600">No properties available</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-100 p-4">
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <h1 className="text-2xl font-bold">RealEstate</h1>
        <div className="flex items-center space-x-2">
          <input
            type="text"
            placeholder="Search..."
            className="border p-1 rounded"
          />
          <button className="bg-blue-500 text-white px-2 py-1 rounded">Search</button>
          <Link to="/">
            <button className="bg-blue-500 text-white px-2 py-1 rounded">Back to Home</button>
          </Link>
        </div>
      </div>
      {/* Filters */}
      <div className="flex flex-wrap space-x-2 mb-4">

        {/* فلتر عدد الغرف */}
        <select
          value={bedrooms}
          onChange={(e) => setBedrooms(e.target.value)}
          className="bg-gray-200 px-2 py-1 rounded"
        >
          <option value="">All Bedrooms</option>
          <option>1</option>
          <option>2</option>
          <option>3</option>
          <option>4</option>
          <option>5</option>
        </select>

        {/* فلتر السعر */}
        <select
          value={priceRange}
          onChange={(e) => setPriceRange(e.target.value)}
          className="bg-gray-200 px-2 py-1 rounded"
        >
          <option value="">All Prices</option>
          <option value="0-5000000">Up to $5M</option>
          <option value="5000001-10000000">$5M - $10M</option>
          <option value="10000001-20000000">$10M - $20M</option>
          <option value="20000001">Above $20M</option>
        </select>


        {/* فلتر عدد الحمامات */}
        <select
          value={bathrooms}
          onChange={(e) => setBathrooms(e.target.value)}
          className="bg-gray-200 px-2 py-1 rounded"
        >
          <option value="">All Bathrooms</option>
          <option>1</option>
          <option>2</option>
          <option>3</option>
          <option>4</option>
          <option>5</option>
        </select>
      </div>

      {/* Listings */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {filteredProperties.map((property) => (
          <div key={property._id} className="bg-white p-4 rounded shadow">
            <img
              src={property.image}
              alt={property.address}
              className="w-full h-40 object-cover rounded"
            />
            <h3 className="text-lg font-semibold mt-2">{property.address}</h3>
            <p className="text-gray-600">
              {property.beds} Beds | {property.baths} Baths
            </p>
            <p className="text-green-600 font-bold mt-2">${property.price.toLocaleString()}</p>

            {property.isSold && (
              <div className="bg-red-100 text-red-800 px-2 py-1 rounded mt-2 text-center font-semibold">
                SOLD
              </div>
            )}

            <div className="flex space-x-2 mt-2 justify-center">
              <button className="bg-green-500 text-white px-2 py-1 rounded hover:bg-green-600">Call</button>
              <button className="bg-blue-500 text-white px-2 py-1 rounded hover:bg-blue-600">Chat</button>
              <button
                onClick={() => handleBuyProperty(property)}
                disabled={property.isSold}
                className={`px-4 py-1 rounded w-60 font-semibold transition ${property.isSold
                  ? 'bg-gray-400 text-gray-700 cursor-not-allowed'
                  : 'bg-blue-500 text-white hover:bg-blue-600'
                  }`}
              >
                {property.isSold ? 'Sold Out' : 'Buy Now'}
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export default Buy;