@echo off
echo Starting Real Estate Marketplace Microservices...

echo Starting Auth Service (Port 3001)...
start "Auth Service" cmd /k "cd microservices\auth-service && npm run start:dev"

echo Starting Property Service (Port 3002)...
start "Property Service" cmd /k "cd microservices\property-service && npm run start:dev"

echo Starting Transaction Service (Port 3003)...
start "Transaction Service" cmd /k "cd microservices\transaction-service && npm run start:dev"

echo Starting Search Service (Port 3004)...
start "Search Service" cmd /k "cd microservices\search-service && npm run start:dev"

echo Starting Analysis Service (Port 3005)...
start "Analysis Service" cmd /k "cd microservices\analysis-service && npm run start:dev"

echo Starting API Gateway (Port 4000)...
start "API Gateway" cmd /k "cd microservices\api-gateway && npm run start:dev"

echo Starting Client...
start "Client" cmd /k "cd client && npm start"

echo All services started!
pause
