<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_w-full px-3 py-2 border rounded_12</name>
   <tag></tag>
   <elementGuidId>a7a67e88-3a30-45b4-8e07-2005de9eb529</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.w-full.px-3.py-2.border.rounded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Astaghfirul']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter property Address&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b767ab95-8122-4f25-854d-36e6f4afe8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter property Address</value>
      <webElementGuid>f281e2fe-242d-4fec-a436-8207187e96ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-3 py-2 border rounded</value>
      <webElementGuid>a606db06-5064-4aba-bb1e-fac426579b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6fdcc793-8584-4385-bf33-8a3d18ef428a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Astaghfirul</value>
      <webElementGuid>374997d0-887f-4438-9a98-fb741f6bd2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wfd-id</name>
      <type>Main</type>
      <value>id5</value>
      <webElementGuid>abaafc46-4cf0-4930-9bfb-376b70672128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-gray-100 p-4&quot;]/div[@class=&quot;max-w-2xl mx-auto bg-white p-6 rounded shadow mt-6&quot;]/form[@class=&quot;space-y-4&quot;]/div[1]/input[@class=&quot;w-full px-3 py-2 border rounded&quot;]</value>
      <webElementGuid>091e80b1-707b-4170-a60f-af95f3d11170</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Astaghfirul']</value>
      <webElementGuid>0f3ba3b2-8e23-463f-b238-ed3e18d6a3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div/input</value>
      <webElementGuid>779ff571-52ce-4208-bac7-834f6c9b77a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c54fe72f-7906-497d-85d7-59f7ce20652c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter property Address' and @type = 'text']</value>
      <webElementGuid>13be4129-a427-4b44-8dba-dd4a1cc0dfcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
